window.PRODUCTOS_DE_PRUEBA = [
  {
    "id": "crm-taller-mecanico",
    "nombre": "CRM Taller Mecánico Profesional",
    "categoria": "Automoción",
    "icono": "fa-car-side",
    "precio": "0,00€",
    "resumen": "Control total de vehículos, órdenes de trabajo y citas en tiempo real.",
    "descripcion": "Maximiza la rentabilidad de tu taller mecánico con una gestión digital impecable. Controla cada matrícula, el historial completo de reparaciones y el seguimiento de recambios sin complicaciones. La herramienta definitiva para talleres que buscan profesionalidad y confianza.",
    "desarrollo": "Sistema optimizado para la recepción de vehículos, asignación de mecánicos, estados de reparación dinámicos y generación de presupuestos precisos. Compatible con cualquier moneda.",
    "incluye": ["Historial clínico por matrícula", "Gestión de Órdenes de Reparación", "Presupuestos en un clic", "Control de stock de recambios", "Seguimiento de estados de trabajo"],
    "seo": "CRM taller mecánico, software gestión taller, programa reparaciones coches, ordenes de trabajo taller."
  },
  {
    "id": "crm-clinica-dental",
    "nombre": "CRM Gestión Clínica Dental",
    "categoria": "Salud",
    "icono": "fa-tooth",
    "precio": "0,00€",
    "resumen": "Agenda odontológica, fichas de pacientes y control de tratamientos especializados.",
    "descripcion": "Digitaliza tu clínica dental con un sistema diseñado para la precisión médica. Gestiona citas, historias clínicas detalladas y planes de tratamiento con una interfaz intuitiva que reduce el tiempo administrativo y mejora la atención al paciente.",
    "desarrollo": "Agenda interactiva por doctor, registro de tratamientos dentales, control de pagos por sesión y gestión de recordatorios automáticos.",
    "incluye": ["Odontograma básico", "Agenda de citas por gabinete", "Ficha técnica del paciente", "Gestión de cobros y facturación", "Presupuestos de tratamientos"],
    "seo": "software clínica dental, CRM odontólogos, gestión pacientes dentista, programa dentista gratuito."
  },
  {
    "id": "crm-clinica-medica",
    "nombre": "CRM Clínica y Consulta Médica",
    "categoria": "Salud",
    "icono": "fa-user-md",
    "precio": "0,00€",
    "resumen": "Gestión de historias clínicas, agenda médica y seguimiento de pacientes.",
    "descripcion": "La solución ideal para consultas privadas y policlínicas. Organiza la atención de tus pacientes con historias clínicas digitales seguras, una agenda de citas eficiente y un control administrativo simplificado que te permite enfocarte en la salud.",
    "desarrollo": "Gestión de expedientes médicos, agenda interactiva, avisos de citas y módulo de facturación médica básica adaptable.",
    "incluye": ["Historia clínica digital", "Agenda médica por profesional", "Gestión de recetas y volantes", "Control de facturación de consultas", "Recordatorios de citas"],
    "seo": "CRM médico, software gestión clínica, programa consulta médica, gestión pacientes salud."
  },
  {
    "id": "crm-hostal-posada",
    "nombre": "CRM Gestión Hostales y Posadas",
    "categoria": "Hostelería",
    "icono": "fa-bed",
    "precio": "0,00€",
    "resumen": "Reserva de habitaciones, control de entradas/salidas y mapa de ocupación visual.",
    "descripcion": "Lleva el control de tu hostal o posada de forma sencilla y eficiente. Visualiza la disponibilidad de habitaciones, gestiona el check-in/out en segundos y mantén un registro claro de tus huéspedes y consumos extra.",
    "desarrollo": "Mapa de ocupación diario, gestión de reservas por tipo de habitación, control de limpieza y facturación simplificada por estancia.",
    "incluye": ["Mapa visual de ocupación", "Gestión de Check-in y Check-out", "Control de cargos extra", "Historial de huéspedes", "Facturación rápida"],
    "seo": "software gestión hostal, CRM posadas, programa reservas hotel pequeño, gestión alojamiento rural."
  },
  {
    "id": "crm-inmobiliaria",
    "nombre": "CRM Gestión Inmobiliaria y Alquileres",
    "categoria": "Inmobiliaria",
    "icono": "fa-house-chimney",
    "precio": "0,00€",
    "resumen": "Control de alquileres de pisos, chalets y habitaciones con gestión de contratos.",
    "descripcion": "La solución completa para agencias inmobiliarias y gestores de patrimonio. Controla el alquiler de pisos, chalets y habitaciones de forma profesional. Gestiona inquilinos, cobros mensuales, vencimientos de contratos y el estado de cada inmueble en tiempo real.",
    "desarrollo": "Base de datos de inmuebles con fotos y características, gestión de propietarios e inquilinos, avisos de cobro y cruce de demandas automático.",
    "incluye": ["Gestión de alquiler de habitaciones", "Control de contratos y vencimientos", "Fichas de pisos y chalets", "Seguimiento de cobros e impagos", "Cruce automático de demandas"],
    "seo": "CRM inmobiliaria alquileres, software gestión pisos, programa alquiler habitaciones, gestión inmobiliaria profesional."
  },
  {
    "id": "crm-tienda-alimentacion",
    "nombre": "CRM Tienda de Alimentación y TPV",
    "categoria": "Ventas",
    "icono": "fa-basket-shopping",
    "precio": "0,00€",
    "resumen": "Ventas rápidas, control de caducidades y gestión de stock de alimentación.",
    "descripcion": "Optimiza tu tienda de alimentación o supermercado con un sistema de ventas ágil y robusto. Controla el stock de productos, gestiona las fechas de caducidad y ofrece un servicio rápido en caja con nuestro terminal de punto de venta integrado.",
    "desarrollo": "Interfaz TPV táctil, gestión de proveedores, control de mermas y caducidades, y cierre de caja diario simplificado.",
    "incluye": ["Terminal de Venta Rápida", "Control de fechas de caducidad", "Gestión de proveedores", "Cierre de caja automático", "Inventario en tiempo real"],
    "seo": "CRM tienda alimentación, software supermercado, TPV alimentación, gestión stock comida."
  },
  {
    "id": "crm-logistica-facturacion",
    "nombre": "CRM Ventas, Facturación y Logística",
    "categoria": "Ventas",
    "icono": "fa-truck-fast",
    "precio": "0,00€",
    "resumen": "Gestión integral de pedidos, facturación masiva y control de expediciones.",
    "descripcion": "La herramienta definitiva para empresas que necesitan conectar sus ventas con la logística. Gestiona pedidos complejos, genera facturas de forma masiva y controla el estado de las expediciones y el almacén desde una única plataforma centralizada.",
    "desarrollo": "Módulo de gestión de pedidos, trazabilidad de envíos, facturación automatizada y control de múltiples almacenes.",
    "incluye": ["Gestión integral de pedidos", "Facturación masiva de ventas", "Control de logística y envíos", "Trazabilidad de almacén", "Informes de ventas avanzados"],
    "seo": "CRM logística, software facturación ventas, gestión expediciones, programa almacén y logística."
  },
  {
    "id": "crm-centro-formacion",
    "nombre": "CRM Centro de Formación y Academias",
    "categoria": "Educación",
    "icono": "fa-graduation-cap",
    "precio": "0,00€",
    "resumen": "Control de matrículas, alumnos, grupos y pagos para academias.",
    "descripcion": "Organiza tu centro de formación con facilidad. Gestiona las matrículas de nuevos alumnos, organiza los grupos por niveles y lleva un control riguroso de los pagos mensuales y la asistencia a clase.",
    "desarrollo": "Gestión de cursos y horarios, fichas de alumno completas, control de asistencia y módulo de facturación de cuotas recurrentes.",
    "incluye": ["Matrículas y alumnos", "Gestión de cursos y grupos", "Control de pagos y cuotas", "Asistencia y notas", "Comunicación con alumnos"],
    "seo": "CRM academia, software gestión formación, programa cursos academias, gestión alumnos centro formación."
  },
  {
    "id": "crm-peluqueria",
    "nombre": "CRM Peluquería y Estética Premium",
    "categoria": "Servicios",
    "icono": "fa-scissors",
    "precio": "0,00€",
    "resumen": "Agenda inteligente y fidelización para salones de belleza y barberías.",
    "descripcion": "Organiza tu salón de belleza con una agenda visual que evita solapamientos. Conoce las preferencias de cada cliente, gestiona bonos de sesiones y aumenta la recurrencia de visitas con un seguimiento profesional.",
    "desarrollo": "Calendario multi-servicio, fichas técnicas de color y estilo, gestión de stock de productos de venta y control de caja diario.",
    "incluye": ["Agenda visual interactiva", "Ficha de estilo del cliente", "Gestión de bonos y packs", "Historial de servicios", "Control de ventas y productos"],
    "seo": "CRM peluquería, software centros estética, agenda barbería profesional, programa gestión belleza."
  },
  {
    "id": "crm-calzado-complementos",
    "nombre": "CRM Tienda de Calzado e Inventario",
    "categoria": "Comercio",
    "icono": "fa-shoe-prints",
    "precio": "0,00€",
    "resumen": "Stock inteligente por tallas y colores con terminal de venta ágil.",
    "descripcion": "Elimina los errores de inventario en tu tienda de moda o calzado. Gestiona variantes de producto (talla/color) de forma masiva y agiliza las ventas en el mostrador con un sistema que entiende tu negocio.",
    "desarrollo": "Matriz de variantes optimizada, alertas automáticas de reposición, gestión de devoluciones y fidelización de clientes por historial de compra.",
    "incluye": ["Gestión masiva de tallas y colores", "Venta rápida en TPV", "Alertas de stock crítico", "Historial de compras del cliente", "Etiquetado de productos"],
    "seo": "CRM calzado, software gestión tallas y colores, programa stock tiendas moda, TPV comercio calzado."
  },
  {
    "id": "crm-ferreteria",
    "nombre": "CRM Gestión de Ferreterías",
    "categoria": "Comercio",
    "icono": "fa-hammer",
    "precio": "0,00€",
    "resumen": "Catálogo masivo de referencias y control de proveedores industriales.",
    "descripcion": "El aliado perfecto para ferreterías con grandes inventarios. Gestiona miles de referencias, controla las ubicaciones en almacén y optimiza los pedidos a proveedores con una herramienta rápida y fiable.",
    "desarrollo": "Buscador ultra-rápido de referencias, gestión de tarifas por volumen, control de pedidos de compra y seguimiento de ventas a profesionales.",
    "incluye": ["Búsqueda rápida por referencia/EAN", "Gestión de proveedores y pedidos", "Control de ubicaciones", "Tarifas personalizadas", "Presupuestos industriales"],
    "seo": "CRM ferretería, software suministros industriales, gestión stock masivo, programa ferretería profesional."
  },
  {
    "id": "crm-facturacion-reformas",
    "nombre": "CRM Facturación y Obras",
    "categoria": "Construcción",
    "icono": "fa-helmet-safety",
    "precio": "0,00€",
    "resumen": "Presupuestos detallados y control de costes para profesionales de la reforma.",
    "descripcion": "Crea presupuestos profesionales por partidas y controla el margen de beneficio de cada obra. Diseñado para autónomos y empresas de construcción que necesitan orden en sus pagos y facturas.",
    "desarrollo": "Módulo de cálculo por unidades de obra, conversión directa a factura, control de certificaciones y pagos parciales.",
    "incluye": ["Presupuestos por partidas de obra", "Facturación automática", "Control de pagos a cuenta", "Seguimiento de costes de materiales", "Informes de beneficio"],
    "seo": "CRM reformas, software presupuestos construcción, programa facturación autónomos obra, gestión proyectos construcción."
  },
  {
    "id": "email-masivo",
    "nombre": "App Marketing Email Masivo",
    "categoria": "Marketing",
    "icono": "fa-paper-plane",
    "precio": "0,00€",
    "resumen": "Campañas de comunicación segmentadas para aumentar tus ventas recurrentes.",
    "descripcion": "Llega directamente a la bandeja de entrada de tus clientes con ofertas personalizadas. Segmenta tu base de datos y lanza campañas de email marketing con alta entregabilidad y resultados medibles.",
    "desarrollo": "Gestión de listas de contactos masivas, plantillas HTML personalizables, integración SMTP profesional y seguimiento de aperturas.",
    "incluye": ["Segmentación inteligente", "Editor de plantillas", "Conexión SMTP segura", "Gestión de suscripciones", "Informes de envío"],
    "seo": "software email masivo, herramienta mailing negocios, gestión campañas correo electrónico, email marketing CRM."
  },
  {
    "id": "crm-restaurante-cafeteria",
    "nombre": "CRM Restaurante y Reservas",
    "categoria": "Hostelería",
    "icono": "fa-utensils",
    "precio": "0,00€",
    "resumen": "Gestión de mesas, reservas y fidelización de comensales.",
    "descripcion": "Mejora la experiencia en tu sala con un control total de las reservas. Conoce los gustos de tus clientes habituales, organiza eventos especiales y optimiza la ocupación de tus mesas cada día.",
    "desarrollo": "Agenda de reservas interactiva, ficha de gustos del comensal, gestión de eventos de grupo y control de aforo.",
    "incluye": ["Libro de reservas digital", "Historial de clientes VIP", "Gestión de menús de grupo", "Control de ocupación de sala", "Ficha de alergias y preferencias"],
    "seo": "CRM restaurante, software gestión reservas mesas, programa fidelización hostelería, gestión eventos restaurante."
  }
]
